// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Models
{
    public partial class Order
    {
        public int OrderId { get; set; }
        public int MemberId { get; set; }
        public int? ProductId { get; set; }
        public string DiscountCode { get; set; }
        public double? Income { get; set; }
        public string Delivary { get; set; }
        public int Amount { get; set; }

        public virtual Discount DiscountCodeNavigation { get; set; }
        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
    }
}