// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Models
{
    public partial class Blog
    {
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public int ArticleId { get; set; }
        public int Floor { get; set; }
        public int MemberId { get; set; }
        public int? ProductId { get; set; }
        public string Article { get; set; }
        public DateTime? Time { get; set; }
        public string ImageName { get; set; }

        public virtual Member Member { get; set; }
        public virtual Product Product { get; set; }
    }
}