// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Models
{
    public partial class CusCake
    {
        public int CusCakeId { get; set; }
        public int MemberId { get; set; }
        public string ForWho { get; set; }
        public string Purpose { get; set; }
        public string Like { get; set; }
        public string Hate { get; set; }
        public DateTime DueDate { get; set; }
        public string Note { get; set; }

        public virtual Member Member { get; set; }
    }
}