// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi.Models
{
    public partial class Discount
    {
        public Discount()
        {
            Order = new HashSet<Order>();
        }

        public string DiscountCode { get; set; }
        public double? Discount1 { get; set; }
        public DateTime? DueDate { get; set; }
        public int? LeftAmount { get; set; }

        public virtual ICollection<Order> Order { get; set; }
    }
}